# deploy.yml
- hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Pull Docker image
      docker_image:
        name: yashmahi04/my-web-app
        source: pull

    - name: Run Docker container
      docker_container:
        name: your-app-container
        image: yashmahi04/my-web-app
        state: started
        ports:
          - "3000:3000"
